---
kind: pipeline
name: python-3-5-alpine-3-9

steps:
- name: build
  image: python:3.5-alpine3.9
  pull: always
  commands:
    - bash scripts/run-tests
---
kind: pipeline
name: python-3-6-alpine-3-9

steps:
- name: build
  image: python:3.6-alpine3.9
  pull: always
  commands:
    - bash scripts/run-tests
---
kind: pipeline
name: python-3-7-alpine-3-9

steps:
- name: build
  image: python:3.7-alpine3.9
  pull: always
  commands:
    - bash scripts/run-tests
---
kind: pipeline
name: python-3-7-alpine-3-7

steps:
- name: build
  image: python:3.7-alpine3.7
  pull: always
  commands:
    - bash scripts/run-tests
