---
kind: pipeline
name: python-3-5-alpine-3-10

services:
  - name: postgresql
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

steps:
- name: build
  image: python:3.5-alpine3.10
  pull: always
  commands:
    - scripts/run-tests
---
kind: pipeline
name: python-3-6-alpine-3-10

services:
  - name: postgresql
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

steps:
- name: build
  image: python:3.6-alpine3.10
  pull: always
  commands:
    - scripts/run-tests
---
kind: pipeline
name: python-3-7-alpine-3-10

services:
  - name: postgresql
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

steps:
- name: build
  image: python:3.7-alpine3.10
  pull: always
  commands:
    - scripts/run-tests
---
kind: pipeline
name: python-3-7-alpine-3-7

services:
  - name: postgresql
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

steps:
- name: build
  image: python:3.7-alpine3.7
  pull: always
  commands:
    - scripts/run-tests
---
kind: pipeline
name: python-3-8-alpine-3-10

services:
  - name: postgresql
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

steps:
- name: build
  image: python:3.8-alpine3.10
  pull: always
  commands:
    - scripts/run-tests
---
kind: pipeline
name: documentation

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: witten/borgmatic-docs
    dockerfile: docs/Dockerfile
  when:
    branch:
      - master
