location:
    # List of source directories to backup. Globs are expanded.
    source_directories:
        - /home
        - /etc
        - /var/log/syslog*

    # Stay in same file system (do not cross mount points).
    #one_file_system: yes

    # Alternate Borg remote executable (defaults to "borg"):
    #remote_path: borg1

    # Path to local or remote repository.
    repository: user@backupserver:sourcehostname.borg

#storage:
    # Passphrase to unlock the encryption key with. Only use on repositories
    # that were initialized with passphrase/repokey encryption. Quote the value
    # if it contains punctuation so it parses correctly. And backslash any
    # quote or backslash literals as well.
    #encryption_passphrase: "foo"

    # Type of compression to use when creating archives. See
    # https://borgbackup.readthedocs.org/en/stable/usage.html#borg-create
    # for details. Defaults to no compression.
    #compression: lz4

    # Umask to be used for borg create.
    #umask: 0077

retention:
    # Retention policy for how many backups to keep in each category. See
    # https://borgbackup.readthedocs.org/en/stable/usage.html#borg-prune for
    # details.
    #keep_within: 3H
    #keep_hourly: 24
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 6
    keep_yearly: 1

    # When pruning, only consider archive names starting with this prefix.
    #prefix: sourcehostname

consistency:
    # List of consistency checks to run: "repository", "archives", or both.
    # Defaults to both. Set to "disabled" to disable all consistency checks.
    # See https://borgbackup.readthedocs.org/en/stable/usage.html#borg-check
    # for details.
    checks:
        - repository
        - archives

    # Restrict the number of checked archives to the last n.
    #check_last: 3
